/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2021-02-21 06:11:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ticketing;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reserve_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write(" \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/header.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/reserve.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/layer_popup.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("    <link rel='stylesheet' href='//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css' />\r\n");
      out.write("    <script src='//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js'></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" \r\n");
      out.write("    <div class=\"header-nav-wrapper\">\r\n");
      out.write("        <header class=\"header\">\r\n");
      out.write("            <div class=\"header-inner\">\r\n");
      out.write("\t            <ul class=\"util\">\r\n");
      out.write("\t            \t<li>\r\n");
      out.write("\t            \t\t<a class=\"logo apps\" href=\"#\"></a>\r\n");
      out.write("\t            \t</li>\r\n");
      out.write("\t            \t<li>\r\n");
      out.write("\t            \t\t<a class=\"logo facebook\" href=\"#\"></a>\r\n");
      out.write("\t            \t</li>\r\n");
      out.write("\t            \t<li>\r\n");
      out.write("\t            \t\t<a class=\"logo instagram\" href=\"#\"></a>\r\n");
      out.write("\t            \t</li>\r\n");
      out.write("\t            \t<li>\r\n");
      out.write("\t            \t\t<a href=\"#\">알뜰한 영화 관람법</a>\r\n");
      out.write("\t            \t</li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header-inner\">\r\n");
      out.write("                \r\n");
      out.write("                 ");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <nav class=\"nav-wrapper\">\r\n");
      out.write("            <div class=\"logo-wrapper\"><a href=\"#\"><img class=\"cgvLogo\" src=\"https://img.cgv.co.kr/R2014/images/title/h1_cgv.png\"></a></div>\r\n");
      out.write("            <div class=\"nav-content\">\r\n");
      out.write("                <div class=\"movieLogo-wrapper\"><img class=\"cgvMovie\" src=\"https://img.cgv.co.kr/R2014/images/title/h2_ticket.png\"></div>\r\n");
      out.write("                <div class=\"nav-inner\">\r\n");
      out.write("                    <div><button>영화</button></div>\r\n");
      out.write("                    <div><button>예매</button></div>\r\n");
      out.write("                    <div><button>극장</button></div>\r\n");
      out.write("                    <div><button>이벤트&컬쳐</button></div>\r\n");
      out.write("                    <div class=\"search-wrapper\"><input><button class=\"searchButton\">검색</button></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div></div>\r\n");
      out.write("            <div></div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"reserve-container\">\r\n");
      out.write("        <div class=\"movie-part\">\r\n");
      out.write("            <div class=\"reserve-title\">영화</div>\r\n");
      out.write("            <div class=\"sort-wrapper\">\r\n");
      out.write("                <div class=\"sort-rate sort-selected\">예매율순</div>\r\n");
      out.write("            </div>\r\n");
      out.write("             <div class=\"movie-list-wrapper\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"theater-part\">\r\n");
      out.write("            <div class=\"reserve-title\">\r\n");
      out.write("                극장\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"theater-container\">\r\n");
      out.write("                <div class=\"theater-wrapper\">\r\n");
      out.write("                    <div class=\"theater-location-wrapper\">\r\n");
      out.write("                        <button class=\"theater-location\">서울(30)</button>\r\n");
      out.write("                        <button class=\"theater-location\">경기(43)</button>\r\n");
      out.write("                        <button class=\"theater-location\">인천(10)</button>\r\n");
      out.write("                        <button class=\"theater-location\">강원(5)</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"theater-place-wrapper\">\r\n");
      out.write("                        <button class=\"theater-place\">천호</button>\r\n");
      out.write("                        <button class=\"theater-place\">강변</button>\r\n");
      out.write("                        <button class=\"theater-place\">건대입구</button>\r\n");
      out.write("                        <button class=\"theater-place\">구로</button>\r\n");
      out.write("                        <button class=\"theater-place\">대학로</button>\r\n");
      out.write("                        <button class=\"theater-place\">동대문</button>\r\n");
      out.write("                        <button class=\"theater-place\">목동</button>\r\n");
      out.write("                        <button class=\"theater-place\">명동</button>\r\n");
      out.write("                        <button class=\"theater-place\">미아</button>\r\n");
      out.write("                        <button class=\"theater-place\">불광</button>\r\n");
      out.write("                        <button class=\"theater-place\">상봉</button>\r\n");
      out.write("                        <button class=\"theater-place\">송파</button>\r\n");
      out.write("                        <button class=\"theater-place\">수유</button>\r\n");
      out.write("                        <button class=\"theater-place\">압구정</button>\r\n");
      out.write("                        <button class=\"theater-place\">여의도</button>\r\n");
      out.write("                        <button class=\"theater-place\">영등포</button>\r\n");
      out.write("                        <button class=\"theater-place\">왕십리</button>\r\n");
      out.write("                        <button class=\"theater-place\">중계</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"day-part\">\r\n");
      out.write("            <div class=\"reserve-title\">날짜</div>\r\n");
      out.write("            <div class=\"reserve-date\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"time-part\">\r\n");
      out.write("            <div class=\"reserve-title\">시간</div>\r\n");
      out.write("            <div class=\"reserve-time\">\r\n");
      out.write("                <div class=\"reserve-where\">4관(IMAX) 6층(총 240석) </div>\r\n");
      out.write("                <div class=\"reserve-time-wrapper\">\r\n");
      out.write("                    <button class=\"reserve-time-button\">\r\n");
      out.write("\t\t\t            <span class=\"reserve-time-want\">12:10</span>\r\n");
      out.write("\t\t\t            <span class=\"reserve-time-remain\">240석</span>\r\n");
      out.write("\t\t          \t</button>\r\n");
      out.write("                    <button class=\"reserve-time-button\">\r\n");
      out.write("\t\t\t            <span class=\"reserve-time-want\">14:25</span>\r\n");
      out.write("\t\t\t            <span class=\"reserve-time-remain\">240석</span>\r\n");
      out.write("\t\t          \t</button>\r\n");
      out.write("                    <button class=\"reserve-time-button\">\r\n");
      out.write("\t\t\t            <span class=\"reserve-time-want\">16:30</span>\r\n");
      out.write("\t\t\t            <span class=\"reserve-time-remain\">240석</span>\r\n");
      out.write("\t\t          \t</button>\r\n");
      out.write("                    <button class=\"reserve-time-button\">\r\n");
      out.write("\t\t\t            <span class=\"reserve-time-want\">18:05</span>\r\n");
      out.write("\t\t\t            <span class=\"reserve-time-remain\">240석</span>\r\n");
      out.write("\t\t          \t</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("\t            <form class=\"moveSeatForm\" action=\"moveSeat\" method=\"post\">\r\n");
      out.write("\t\t            <input type=\"hidden\" class=\"title\" name=\"title\">\r\n");
      out.write("\t\t            <input type=\"hidden\" class=\"movieAge\" name=\"movieAge\">\r\n");
      out.write("\t\t            <input type=\"hidden\" class=\"selectedTheater\" name=\"selectedTheater\">\r\n");
      out.write("\t\t            <input type=\"hidden\" class=\"reserveDate\" name=\"movieDate\">\r\n");
      out.write("\t\t            <input type=\"hidden\" class=\"runningTime\" name=\"runningTime\">\r\n");
      out.write("\t\t            <button class=\"moveSeatButton\" type=\"button\">좌석선택</button>\r\n");
      out.write("\t            </form>\r\n");
      out.write("            </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <!-- 팝업창 -->\r\n");
      out.write("       <div class=\"popup\" style=\"display:none;\">\r\n");
      out.write("       \t<div class=\"popup_layer\">\r\n");
      out.write("       \t\t<div class=\"text_area\">\r\n");
      out.write("       \t\t\t<strong class=\"title\">예약 최종 확인</strong>\r\n");
      out.write("       \t\t\t<p class=\"text\"></p>\r\n");
      out.write("       \t\t</div>\r\n");
      out.write("       \t\t<div class=\"btn_area\">\r\n");
      out.write("       \t\t\t<button type=\"button\" name=\"button\" class=\"btn\">예</button>\r\n");
      out.write("       \t\t\t<button type=\"button\" name=\"button\" class=\"btn no\">아니오</button>\r\n");
      out.write("       \t\t</div>\r\n");
      out.write("       \t</div>\r\n");
      out.write("       \t<div class=\"popup_dimmed\"></div>\r\n");
      out.write("       </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"resources/js/reserve.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
