/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2021-02-27 13:51:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ticketing;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kdis.demo.vo.ReserveDto;

public final class seat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kdis.demo.vo.ReserveDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write('\r');
      out.write('\n');
  ReserveDto reserve = (ReserveDto) request.getAttribute("reserve");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write(" \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/header.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/layer_popup.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/seat.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("    <link rel='stylesheet' href='//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css' />\r\n");
      out.write("    <script src='//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js'></script>\r\n");
      out.write("    <script src=\"https://www.paypal.com/sdk/js?client-id=AQPrrIuemnOd2qvQmtxdrRwxteZcdhs3o-0y5hZxVAdr5NqGarbDmeY0jExpXYGIVXDVK7oRpRqJ6yhz\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" \r\n");
      out.write("    <div class=\"header-nav-wrapper\">\r\n");
      out.write("        <header class=\"header\">\r\n");
      out.write("            <div class=\"header-inner\">\r\n");
      out.write("\t            <ul class=\"util\">\r\n");
      out.write("\t            \t<li>\r\n");
      out.write("\t            \t\t<a class=\"logo apps\" href=\"#\"></a>\r\n");
      out.write("\t            \t</li>\r\n");
      out.write("\t            \t<li>\r\n");
      out.write("\t            \t\t<a class=\"logo facebook\" href=\"#\"></a>\r\n");
      out.write("\t            \t</li>\r\n");
      out.write("\t            \t<li>\r\n");
      out.write("\t            \t\t<a class=\"logo instagram\" href=\"#\"></a>\r\n");
      out.write("\t            \t</li>\r\n");
      out.write("\t            \t<li>\r\n");
      out.write("\t            \t\t<a href=\"#\">알뜰한 영화 관람법</a>\r\n");
      out.write("\t            \t</li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header-inner\">\r\n");
      out.write("                \r\n");
      out.write("                 ");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <nav class=\"nav-wrapper\">\r\n");
      out.write("            <div class=\"logo-wrapper\"><a href=\"#\"><img class=\"cgvLogo\" src=\"https://img.cgv.co.kr/R2014/images/title/h1_cgv.png\"></a></div>\r\n");
      out.write("            <div class=\"nav-content\">\r\n");
      out.write("                <div class=\"movieLogo-wrapper\"><img class=\"cgvMovie\" src=\"https://img.cgv.co.kr/R2014/images/title/h2_ticket.png\"></div>\r\n");
      out.write("                <div class=\"nav-inner\">\r\n");
      out.write("                    <div><button>영화</button></div>\r\n");
      out.write("                    <div><button>예매</button></div>\r\n");
      out.write("                    <div><button>극장</button></div>\r\n");
      out.write("                    <div><button>이벤트&컬쳐</button></div>\r\n");
      out.write("                    <div class=\"search-wrapper\"><input><button class=\"searchButton\">검색</button></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div></div>\r\n");
      out.write("            <div></div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<div class=\"select-container\">\r\n");
      out.write("\t\t<div class=\"select-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"select-title\">인원/좌석</div>\r\n");
      out.write("\t\t\t<div class=\"select-seat-container\">\r\n");
      out.write("\t\t\t\t<div class=\"select-seat-number-container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"select-seat-number-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"select-seat\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"select-seat-age\">일반</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"select-seat-number\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"select-seat-ul select-seat-ul-normal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"select-number-normal\">0</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"select-number-normal\">1</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"select-number-normal\">2</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"select-number-normal\">3</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"select-number-normal\">4</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"select-seat\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"select-seat-age\">청소년</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"select-seat-number\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"select-seat-ul select-seat-ul-teen\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"select-number-teen\">0</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"select-number-teen\">1</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"select-number-teen\">2</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"select-number-teen\">3</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"select-number-teen\">4</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"select-seat\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"select-seat-age\">우대</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"select-seat-number\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"select-seat-ul select-seat-ul-old\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"select-number-old\">0</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"select-number-old\">1</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"select-number-old\">2</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"select-number-old\">3</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"select-number-old\">4</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"coupon\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"coupon_btn\">관람 할인</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"select-seat-information\">\r\n");
      out.write("\t\t\t\t\t<div class=\"selected-movie\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reserve.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"select-seat-information-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"select-theater-place selected-theater-place-info\">CGV강남</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"select-theater-place selected-theater-place-info\">4관\r\n");
      out.write("\t\t\t\t\t\t\t6층</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"select-theater-place\">\r\n");
      out.write("\t\t\t\t\t\t\t<span>남은좌석</span><span class=\"remain-seats\">240</span>/<span class=\"all-seats\">240</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"select-theater-date\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"theater-date\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reserve.movieDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"theater-time\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reserve.runningTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"selected-seats-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"selected-seats-title\">좌석번호</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"selected-seats\">선택된 좌석이 없습니다.</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"ticket-price-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"ticket-price-title\">가격</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"ticket-price\">0원</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"payment-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"payment-title\">결제하기</span>\r\n");
      out.write("\t\t\t\t\t\t<form class=\"seatForm\" action=\"moveReserve\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" class=\"title\" name=\"title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reserve.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t            <input type=\"hidden\" class=\"movieAge\" name=\"movieAge\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reserve.movieAge}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t            <input type=\"hidden\" class=\"selectedTheater\" name=\"selectedTheater\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reserve.selectedTheater}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t            <input type=\"hidden\" class=\"reserveDate\" name=\"movieDate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reserve.movieDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t            <input type=\"hidden\" class=\"runningTime\" name=\"runningTime\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reserve.runningTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t            <!-- 티켓 정보 -->\r\n");
      out.write("\t\t\t\t            <input type=\"hidden\" class=\"selectedSeat\" name=\"selectedSeat\">\r\n");
      out.write("\t\t\t\t            <input type=\"hidden\" class=\"payMoney\" name=\"payMoney\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"reserve-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"reserve-btn-wrapper\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"seat-container\">\r\n");
      out.write("\t\t\t\t<div class=\"seat-wrapper\">\r\n");
      out.write("\t\t\t\t\t<div class=\"screen-view-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"screen-view\">SCREEN</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 팝업창 -->\r\n");
      out.write("       <div class=\"popup\" style=\"display:none;\">\r\n");
      out.write("       \t<div class=\"popup_layer\">\r\n");
      out.write("       \t\t<div class=\"text_area\">\r\n");
      out.write("       \t\t\t<button type=\"button\" class=\"close-btn\">x</button>\r\n");
      out.write("       \t\t\t<strong class=\"title\">쿠폰 번호 입력</strong>\r\n");
      out.write("       \t\t\t<input type=\"text\" id=\"coupon-number\" class=\"coupon-number\" name=\"coupon-number\" maxlength=\"8\" placeholder=\"쿠폰번호를 입력해주세요\">\r\n");
      out.write("       \t\t\t<button type=\"button\" class=\"coupon-find\">확인</button>\r\n");
      out.write("       \t\t</div>\r\n");
      out.write("       \t</div>\r\n");
      out.write("       \t<div class=\"popup_dimmed\"></div>\r\n");
      out.write("       </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"resources/js/seat.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
